# Generated by Django 3.2 on 2021-04-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['PrdCreated'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
