# Generated by Django 3.2 on 2021-04-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-PrdCreated'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
