# Generated by Django 3.2 on 2021-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default=1, max_length=15, verbose_name='Mobile'),
            preserve_default=False,
        ),
    ]
