# Generated by Django 3.1.7 on 2021-05-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210520_1738'),
        ('accounts', '0005_auto_20210520_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='product_favorites',
            field=models.ManyToManyField(to='products.Product', verbose_name='Product Favorites'),
        ),
    ]
