# Generated by Django 3.1.7 on 2021-05-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210523_2010'),
        ('accounts', '0008_auto_20210523_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='product_favorites',
            field=models.ManyToManyField(to='products.Product', verbose_name='Product Favorites'),
        ),
    ]
