# Generated by Django 3.2 on 2021-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_id'),
        ('accounts', '0012_auto_20210526_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='product_favorites',
            field=models.ManyToManyField(to='products.Product', verbose_name='Product Favorites'),
        ),
    ]
